version: '3.6'

services:
  omt:
    image: comsave/salesforce-outbound-message-tower:master
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    ports:
      - 49999:80
    depends_on:
      - redis

  redis:
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes