index:
    path: /
    controller: App\Controller\IndexController::index

broadcast:
    path: /broadcast
    controller: App\Controller\BroadcastController::broadcast

broadcast_processed:
    path: /broadcast/processed
    controller: App\Controller\BroadcastController::broadcastProcessed