index:
    path: /
    controller: App\Controller\IndexController::index

broadcast:
    path: /{channelName}/broadcast
    controller: App\Controller\BroadcasterController::broadcast

broadcast_processed:
    path: /{channelName}/broadcast/processed/{notificationId}
    controller: App\Controller\BroadcasterController::broadcastProcessed

receiver:
    path: /{channelName}/receive
    controller: App\Controller\ReceiverController::receiveMessage