index:
    path: /
    controller: App\Controller\IndexController::index

broadcast:
    path: /broadcast
    controller: App\Controller\BroadcasterController::broadcast

broadcast_processed:
    path: /broadcast/processed
    controller: App\Controller\BroadcasterController::broadcastProcessed

receiver:
    path: /receive
    controller: App\Controller\ReceiverController::receiveMessage