parameters:
    slack_token: '%env(SLACK_TOKEN)%'
    slack_bot_name: '@@tower'
    slack_channel: '#monitoring'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Services\AccessManager:
        arguments:
            $userIpRequestHeaderName: '%env(APP_USER_IP_REQUEST_HEADER)%'
            $alloweadIps: '%env(APP_ALLOWED_IP_ADDRESSES)%'