parameters:
    broadcast_messages_dir: '../%env(APP_BROADCAST_MESSAGES_DIR)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Services\Factory\BroadcastMessagePathFactory:
        arguments:
            $broadcastMessagesDir: '%broadcast_messages_dir%'

    App\Services\AccessManager:
        arguments:
            $userIpRequestHeaderName: '%env(APP_SALESFORCE_SERVER_IPS)%'
            $salesforceServerIps: '%env(APP_SALESFORCE_SERVER_IPS)%'
            $towerClientIps: '%env(APP_TOWER_CLIENT_IPS)%'